TYPE_MENU = "type_menu"

ACTION_ADD = "action_add"
ACTION_ADD_LIST = "action_add_list"
ACTION_REMOVE = "action_remove"
ACTION_LIST_ALL = "action_list_all"
ACTION_FILTER_ABOVE = "action_filter_above"
ACTION_UNDO = "action_undo"
ACTION_EXIT = "action_exit"
ACTION_ERROR = "action_error"
ACTION_HELP = "action_help"
